
ifeval::["{revlifecycle}" == "dev"]
[WARNING]
.This document is in the link:http://riscv.org/spec-state[Development state]
====
Assume everything can change.
====
endif::[]
ifeval::["{revlifecycle}" == "stable"]
[WARNING]
.This document is in the link:http://riscv.org/spec-state[Stable state]
====
Assume anything could still change, but limited change should be expected.
====
endif::[]
ifeval::["{revlifecycle}" == "frozen"]
[WARNING]
.This document is in the link:http://riscv.org/spec-state[Frozen state]
====
Change is extremely unlikely. A high threshold will be used, and a change will
only occur because of some truly critical issue being identified during the
public review cycle.
====
endif::[]
ifeval::["{revlifecycle}" == "ratified"]
[WARNING]
.This document is in the link:http://riscv.org/spec-state[Ratified state]
====
No changes are allowed. Any desired or needed changes can be the subject of
a follow-on new extension. Ratified extensions are never revised.
====
endif::[]

Contributors to all versions of the spec in alphabetical order:

Alex Bradbury,
Andrew Burgess,
Chih-Mao Chen,
Zakk Chen,
Kito Cheng,
Nelson Chu,
Michael Clark,
Jessica Clarke,
Palmer Dabbelt,
Sam Elliott,
Gonzalo Brito Gadeschi,
Sebastian Huber,
Roger Ferrer Ibanez,
Quey-Liang Kao,
Nick Knight,
Luís Marques,
Evandro Menezes,
Max Nordlund,
Stefan O'Rear,
Konrad Schwarz,
Fangrui Song,
Hsiangkai Wang,
Andrew Waterman,
Jim Wilson

It is licensed under the Creative Commons Attribution 4.0 International
License (CC-BY 4.0).  The full license text is available at
https://creativecommons.org/licenses/by/4.0/.

Please cite as: `RISC-V ABIs Specification,
 Document Version {refrev}', Editors
Kito Cheng and Jessica Clarke, RISC-V International, {monthyear}.

The latest version of this document can be found here:
https://github.com/riscv-non-isa/riscv-elf-psabi-doc.

This specification is written in collaboration with the development communities
of the major open-source toolchain and operating system communities, and as
such specifies what has been agreed upon and implemented. As a result, any
changes to this specification that are not backwards-compatible would break ABI
compatibility for those toolchains, which is not permitted unless for features
explicitly marked as experimental, and so will not be made unless absolutely
necessary, regardless of whether the specification is a pre-release version,
ratified version or anything in between. This means any version of this
specification published at the above link can be regarded as stable in the
technical sense of the word (but not necessarily in the official RISC-V
International specification state meaning), with the official specification
state being an indicator of the completeness, clarity and general editorial
quality of the specification.
