[[riscv-dwarf]]
= RISC-V DWARF Specification
ifeval::["{docname}" == "riscv-dwarf"]
include::prelude.adoc[]
endif::[]

== DWARF Debugging Format

The DWARF debugging format for RISC-V follows the
https://dwarfstd.org/[standard DWARF specification]; this specification only
describes RISC-V-specific definitions.

== DWARF Register Numbers

[cols="2,2,4"]
[width=80%]
|===
| DWARF Number | Register Name | Description

| 0 - 31       | x0 - x31      | Integer Registers
| 32 - 63      | f0 - f31      | Floating-point Registers
| 64           |               | Alternate Frame Return Column
| 65 - 95      |               | Reserved for future standard extensions
| 96 - 127     | v0 - v31      | Vector Registers
| 128 - 3071   |               | Reserved for future standard extensions
| 3072 - 4095  |               | Reserved for custom extensions
| 4096 - 8191  |               | CSRs
|===

The alternate frame return column is meant to be used when unwinding from
signal handlers, and stores the address where the signal handler will return
to.

There is space for 4096 CSRs. Each CSR is assigned a DWARF register number
corresponding to its CSR number given in **Volume II: Privileged Architecture**
of **The RISC-V Instruction Set Manual** plus 4096.
